[build]

  [[buildpacks]]
  id = "tanzu-buildpacks/nodejs"

  [[buildpacks]]
  id = "tanzu-buildpacks/nginx"

  [[ build.env ]]
    name="BP_NODE_RUN_SCRIPTS"
    value="build"

  [[ build.env ]]
    name="BP_WEB_SERVER"
    value="nginx"

  [[ build.env ]]
    name="BP_WEB_SERVER_ROOT"
    value="dist"

  [[ build.env ]]
    name="BP_WEB_SERVER_ENABLE_PUSH_STATE"
    value="true"
